[".config/wezterm"]
  type = "git-repo"
  url = "https://github.com/sravioli/wezterm/archive/main.tar.gz"


[".config/nvim"]
  type = "git-repo"
  exact = true
  url = "https://github.com/sravioli/nvim/archive/main.tar.gz"

["/usr/src/neovim"]
  type = "git-repo"
  exact = true
  url = "https://github.com/neovim/neovim/archive/main.tar.gz"
